// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestATOH1.Models.DataBaseContext;

#nullable disable

namespace TestATOH1.Migrations
{
    [DbContext(typeof(UsersDbContext))]
    [Migration("20240513185844_V1")]
    partial class V1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TestATOH1.Models.UserModel", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Admin")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Birthday")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RevokedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RevokedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Guid");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Guid = new Guid("4b9d4258-4f99-4264-b6c9-0a5d3202e37f"),
                            Admin = true,
                            Birthday = new DateTime(2024, 5, 13, 21, 58, 43, 629, DateTimeKind.Local).AddTicks(9547),
                            CreatedBy = "admin",
                            CreatedOn = new DateTime(2024, 5, 13, 21, 58, 43, 629, DateTimeKind.Local).AddTicks(9570),
                            Gender = 1,
                            Login = "Admin",
                            ModifiedBy = "admin",
                            ModifiedOn = new DateTime(2024, 5, 13, 21, 58, 43, 629, DateTimeKind.Local).AddTicks(9572),
                            Name = "Max",
                            Password = "admin",
                            RevokedBy = "admin",
                            RevokedOn = new DateTime(2024, 5, 13, 21, 58, 43, 629, DateTimeKind.Local).AddTicks(9574)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
